//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public int Turnament { get; set; }
        public string Competition { get; set; }
        public int Player { get; set; }
        public int PlayerScore { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<decimal> Time { get; set; }
        public Nullable<decimal> FinalScore { get; set; }
    
        public virtual Competitions Competitions { get; set; }
        public virtual Players Players { get; set; }
        public virtual Turnament Turnament1 { get; set; }
    }
}
